# Generated by Django 2.2.3 on 2019-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='927778', max_length=255),
        ),
    ]
